In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import product
import random
import math
import pickle
from tqdm.notebook import tqdm_notebook
import sys
sys.path.append('../')
import fn
from addition_dataset import GroupAddition

/Users/cutterdawes/Desktop/Princeton/Thesis/Repo/ml/../fn.py:6: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm


In [2]:
%load_ext autoreload
%autoreload 2

## Testing

In [3]:
b = 4

In [16]:
table = 1*(np.add.outer(np.arange(b),np.arange(b))>=b)

In [17]:
table

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 1, 1, 1]])

In [39]:
dataset = GroupAddition(table, 2, ids=None, interleaved=True, digit_order='reversed')

In [40]:
dataset[0]

(tensor([[0., 1., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([2, 2]),
 tensor([2, 5]))

In [31]:
g1 = fn.RecursiveGrpElt((2, 0), table)
g2 = fn.RecursiveGrpElt((0, 1), table)
(g1 + g2).vals

(2, 1)